FROM nginx:latest
LABEL maintainer 'Vinicius Anicácio <anicaciovinicius36@gmail.com'

RUN echo '<body style="background-color: black"><h1 style="color: red">No content</h1></h1>' > /usr/share/nginx/html/content.html
COPY *.html /usr/share/nginx/html